config/routes.rb
Rails.application.routes.draw do

   root 'ticket_portal#portal'

   resources :airports, :states, :users, :user_sessions, :airplanes, :trips, :tickets

   get 'faq' => 'static_pages#faq', :as => :faq
   get 'contacts' => 'static_pages#contacts', :as => :contacts
   get 'terms' => 'static_pages#terms', :as => :terms

   get 'login' => 'user_sessions#new', :as => :login
   get 'logout' => 'user_sessions#destroy', :as => :logout

   get 'panel' => 'admin_pages#panel', :as => :panel

   get 'portal' => 'ticket_portal#portal', :as => :portal
   get 'search' => 'ticket_portal#search', :as => :search
   get 'my_tickets' => 'ticket_portal#my_tickets', :as => :my_tickets

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |auth|
  end

  has_many :trips
  has_many :tickets


  def is_admin?
    if self.level == 'admin'
      true
    else
      false
    end
  end

  def is_online?
    if self.last_request_at.nil?
      return false
    else
      if self.last_request_at > 15.minutes.ago
        return true
      else
        return false
      end
    end
  end

  validates_presence_of :email, :on => :create
  validates_presence_of :password_confirmation, :on => :create
  validates_presence_of :email_confirmation, :on => :create
  validates :email, :confirmation => true, :on => :create
  validates :password, :confirmation => true, :on => :create

  validates :email, :uniqueness => true
  validates :login, :uniqueness => true
  validates :login, :length => {:minimum => 4, :maximum => 16}
  validates :password, :length => {:minimum => 6}, :on => :create
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController

  before_filter :request_admin, only: [:destroy, :index]


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'Registrace dokončena.' }
        format.json { head :no_content }

      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Uživatel smazán.' }
      format.json { head :no_content }
    end

  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Uživatel nenalezen.'
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def edit
    @user = User.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Uživatel nenalezen.'
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html { render :layout => 'admin' }
      format.json { head :no_content }
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user.is_admin? || current_user == @user
      return redirect_to root_path
    end

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Uživatel nenalezen.'
  end

  def update
    @user = User.find(params[:id])
    unless current_user.is_admin? || current_user != @user
      return redirect_to root_path
    end

    respond_to do |format|
      if @user.user_attributes(user_params)
        format.html { redirect_to root_path, notice: 'Uživatel byl upraven.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  protected
  def user_params
    params.require(:user).permit(:login, :email, :email_confirmation, :password, :password_confirmation, :name)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="page-header">
  <h1>Seznam uživatelů</h1>
</div>

<div class="col-md-12">
  <table class="table table-hover table-striped">
    <thead>
        <tr>
          <th>Přihlašovací jméno</th>
          <th>Jméno</th>
          <th>Email</th>
          <th>Datum registrace</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.login, user %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at %></td>
              <td><%= link_to 'Smazat', user_path(user), :method => :delete,
                              :confirm => 'Opravdu chcete smazat tohoto uživatele?',
                              :class => 'btn btn-medium btn-danger'%></td>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Registrace nového uživatele</h1>
</div>

<%= provide(:title, ' - Registrace') %>

<style type="text/css">
    .append-required {
        color: indianred;
    }
</style>

<div class="col-md-6">
  <%= form_for(@user) do |sign_up| %>

      <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <h2>Registrace se nezdařila:</h2>

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= sign_up.label :login, content_tag(:b, 'Přihlašovací jméno'), :class => 'control-label' %>
        <div class="input-group input-append">
          <%= sign_up.text_field :login, :class => 'form-control' %>
          <span class="input-group-addon append-required">Povinné</span>
        </div>
      </div>

      <div class="form-group">
        <%= sign_up.label :email, content_tag(:b, 'Email'), :class => 'control-label' %>
        <div class="input-group input-append">
          <span class="input-group-addon"><i class="glyphicon glyphglyphicon glyphicon-envelope"></i></span>
          <%= sign_up.text_field :email, :class => 'form-control', :id => 'inputIcon' %>
          <span class="input-group-addon append-required">Povinné</span>
        </div>
      </div>

      <div class="form-group">
        <%= sign_up.label :email_confirmation, content_tag(:b, 'Potvrzení emailu'), :class => 'control-label' %>
        <div class="input-group input-append">
          <span class="input-group-addon">
            <i class="glyphicon glyphglyphicon glyphicon-envelope"></i></span>
          <%= sign_up.text_field :email_confirmation, :class => 'form-control', :id => 'inputIcon' %>
          <span class="input-group-addon append-required">Povinné</span>
        </div>
      </div>


      <div class="form-group">
        <%= sign_up.label :password, content_tag(:b, 'Heslo'), :class => 'control-label' %>
        <div class="input-group input-append">
          <span class="input-group-addon"><i class="glyphicon glyphglyphicon glyphicon-lock"></i></span>
          <%= sign_up.password_field :password, :class => 'form-control' %>
          <span class="input-group-addon append-required">Povinné</span>
        </div>
        <%= sign_up.label :password_confirmation, content_tag(:b, 'Potvrzení hesla'), :class => 'control-label' %>
        <div class="input-group input-append">
          <span class="input-group-addon"><i class="glyphicon glyphglyphicon glyphicon-lock"></i></span>
          <%= sign_up.password_field :password_confirmation, :class => 'form-control' %>
          <span class="input-group-addon append-required">Povinné</span>
        </div>
        <i>Heslo musí být dlouhé alespoň 6 znaků.</i>
      </div>


      <div class="form-group">
        <%= sign_up.label :name, content_tag(:b, 'Jméno'), :class => 'control-label' %>
        <div class="controls">
          <div class="input-group">
            <%= sign_up.text_field :name, :class => 'form-control' %>
          </div>
        </div>
      </div>


      <p>Kliknutím na tlačítko Vytvořit účet automaticky souhlasíte s <%= link_to 'podmínky služeb', terms_path %>.

      <div class="form-group">
        <%= sign_up.submit 'Vytvořit účet', class: 'btn btn-medium btn-primary' %>
      </div>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.login %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Přihlašovací jméno</dt>
  <dd><%= @user.login %></dd>
  <dt>Jméno</dt>
  <dd><%= @user.name %></dd>
  <dt>Email</dt>
  <dd><%= @user.email %></dd>
  <% if current_user.is_admin? %>
      <dt>Oprávnění</dt>
      <dd><%= current_user.level %></dd>
  <% end %>
</dl>
<%= link_to 'Upravit údaje', edit_user_path(@user)%>

<% if current_user.is_admin? %>
    <%= link_to 'Smazat', @user, :method => :delete, :confirm => 'Opravdu chcete smazat tohoto uživatele?',
                :class => 'btn btn-medium btn-danger' %>
<% end %>

<%= link_to 'Mé letenky (HTML)', my_tickets_path(format: :html), :class => 'btn btn-medium btn-info'  %>
<%= link_to 'Mé letenky (XML)', my_tickets_path(format: :xml), :class => 'btn btn-medium btn-info'  %>