config/routes.rb
Rails.application.routes.draw do

   root 'ticket_portal#portal'

   resources :airports, :states, :users, :user_sessions, :airplanes, :trips, :tickets

   get 'faq' => 'static_pages#faq', :as => :faq
   get 'contacts' => 'static_pages#contacts', :as => :contacts
   get 'terms' => 'static_pages#terms', :as => :terms

   get 'login' => 'user_sessions#new', :as => :login
   get 'logout' => 'user_sessions#destroy', :as => :logout

   get 'panel' => 'admin_pages#panel', :as => :panel

   get 'portal' => 'ticket_portal#portal', :as => :portal
   get 'search' => 'ticket_portal#search', :as => :search
   get 'my_tickets' => 'ticket_portal#my_tickets', :as => :my_tickets

end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :airports

  validates_presence_of :name
end

app/controllers/states_controller.rb
# encoding: utf-8

class StatesController < ApplicationController

  before_filter :request_admin
  layout 'admin'


  def create
    @state = State.new(states_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to states_path, notice: 'Země vytvořena.' }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_path, notice: 'Země smazána.' }
      format.json { head :no_content }
    end

  rescue ActiveRecord::RecordNotFound
    return redirect_to states_path, alert: 'Země nenalezena.'
  end

  def new
    @state = State.new

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def edit
    @state = State.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to states_path, alert: 'Země nenalezena.'
  end

  def index
    @states = State.all

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Země nenalezena.'
  end

  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(states_params)
        format.html { redirect_to states_path, notice: 'Země bylo upravena.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  protected
  def states_params
    params.require(:state).permit(:name)
  end


end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="col-md-6">
  <%= form_for(@state) do |state| %>

      <% if @state.errors.any? %>
          <div class="alert alert-danger">
            <h2>Uložení země se nezdařilo:</h2>

            <ul>
              <% @state.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= state.label :name, content_tag(:b, 'Název Země'), :class => 'control-label' %>
        <%= state.text_field :name, :class => 'form-control' %>
      </div>


      <div class="form-group">
        <%= state.submit 'Odeslat', class: 'btn btn-medium btn-primary' %>
      </div>
  <% end %>
</div>

app/views/states/edit.html.erb
<%= provide(:title, ' - Editace země') %>
<div class="page-header">
  <h1>Editace země</h1>
</div>


<%= render 'form' %>

app/views/states/index.html.erb
<div class="page-header">
  <h1>Seznam Zemí</h1>
</div>

<table class="table table-hover table-striped">
  <thead>
  <tr>
    <th>Název</th>
    <th>Datum vytvoření</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @states.each do |state| %>
      <tr>
        <td><%= link_to state.name, state %></td>
        <td><%= state.created_at %></td>
        <td><%= link_to 'Smazat', state_path(state), :method => :delete,
                        :confirm => 'Opravdu chcete smazat tuto zemi?',
                        :class => 'btn btn-medium btn-danger' %>
          <%= link_to 'Editovat', edit_state_path(state), :class => 'btn btn-medium btn-info' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Nová zem', new_state_path, :class => 'btn btn-medium btn-primary' %>

app/views/states/new.html.erb
<%= provide(:title, ' - Vytvoření nové země') %>
<div class="page-header">
  <h1>Vytvoření nové země</h1>
</div>


<%= render 'form' %>

app/views/states/show.html.erb
<div class="page-header">
  <h1><%= @state.name %></h1>
</div>


<b>Seznam letišt v této zemi</b>
  <table class="table table-hover table-striped">
    <thead>
    <tr>
      <th>Přihlašovací jméno</th>
      <th>Jméno</th>
      <th>Email</th>
      <th>Datum registrace</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @state.airports.each do |airport| %>
        <tr>
          <td><%= link_to airport.name, airport %></td>
          <td><%= airport.created_at %></td>
          <td><%= link_to 'Smazat', airplane_path(airport), :method => :delete,
                          :confirm => 'Opravdu chcete smazat toto letiště?',
                          :class => 'btn btn-medium btn-danger'%></td>
        </tr>
    <% end %>
    </tbody>
  </table>