config/routes.rb
Rails.application.routes.draw do

   root 'ticket_portal#portal'

   resources :airports, :states, :users, :user_sessions, :airplanes, :trips, :tickets

   get 'faq' => 'static_pages#faq', :as => :faq
   get 'contacts' => 'static_pages#contacts', :as => :contacts
   get 'terms' => 'static_pages#terms', :as => :terms

   get 'login' => 'user_sessions#new', :as => :login
   get 'logout' => 'user_sessions#destroy', :as => :logout

   get 'panel' => 'admin_pages#panel', :as => :panel

   get 'portal' => 'ticket_portal#portal', :as => :portal
   get 'search' => 'ticket_portal#search', :as => :search
   get 'my_tickets' => 'ticket_portal#my_tickets', :as => :my_tickets

end

app/models/airport.rb
class Airport < ActiveRecord::Base

  belongs_to :state

  has_many :departures, :class_name => 'Trip', :foreign_key => :from_airport_id
  has_many :arrivals, :class_name => 'Trip', :foreign_key => :to_airport_id

  def count_trips
     departures.count + arrivals.count
  end

  validates_presence_of :name, :state_id
end

app/controllers/airports_controller.rb
# encoding: utf-8

class AirportsController < ApplicationController

  before_filter :request_admin
  layout 'admin'

  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to airports_path, notice: 'Letiště vytvořeno.' }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to airports_path, notice: 'Letiště smazáno.' }
      format.json { head :no_content }
    end

  rescue ActiveRecord::RecordNotFound
    return redirect_to airports_path, alert: 'Letiště nenalezeno.'
  end

  def new
    @airport = Airport.new

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def edit
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to airports_path, alert: 'Letiště nenalezeno.'
  end

  def index
    @airports = Airport.all

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def show
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Letiště nenalezeno.'
  end

  def update
    @airport = Airport.find(params[:id])

    respond_to do |format|
      if @airport.update_attributes(airport_params)
        format.html { redirect_to airports_path, notice: 'Letiště bylo upraveno.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  protected
  def airport_params
    params.require(:airport).permit(:name, :state_id)
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<div class="col-md-6">
  <%= form_for(@airport) do |airport| %>

      <% if @airport.errors.any? %>
          <div class="alert alert-danger">
            <h2>Uložení letiště se nezdařilo:</h2>

            <ul>
              <% @airport.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= airport.label :name, content_tag(:b, 'Název Letiště'), :class => 'control-label' %>
        <%= airport.text_field :name, :class => 'form-control' %>
      </div>

        <div class="form-group">
          <%= airport.label :state_id, content_tag(:b, 'Země'), :class => 'control-label' %>
          <%= collection_select(:airport, :state_id, State.all, :id, :name, {}, {:class => 'form-control'}) %>
        </div>
      
      <div class="form-group">
        <%= airport.submit 'Odeslat', class: 'btn btn-medium btn-primary' %>
      </div>
  <% end %>
</div>

app/views/airports/edit.html.erb
<% provide(:title, '- Editace letiště') %>
<div class="page-header">
  <h1>Editace letiště <%= @airport.name %></h1>
</div>

<%= render 'form' %>

app/views/airports/index.html.erb
<div class="page-header">
  <h1>Seznam letišt</h1>
</div>

<table class="table table-hover table-striped">
  <thead>
  <tr>
    <th>Název</th>
    <th>Stát</th>
    <th>Datum vytvoření</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @airports.each do |airport| %>
      <tr>
        <td><%= link_to airport.name, airport %></td>
        <td><%= link_to airport.state.name, airport.state %></td>
        <td><%= airport.created_at %></td>
        <td><%= link_to 'Smazat', state_path(airport), :method => :delete,
                        :confirm => 'Opravdu chcete smazat toto letiště?',
                        :class => 'btn btn-medium btn-danger' %>
          <%= link_to 'Editovat', edit_airport_path(airport), :class => 'btn btn-medium btn-info' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Nové letiště', new_airport_path, :class => 'btn btn-medium btn-primary' %>

app/views/airports/new.html.erb
<% provide(:title, '- Nové letiště') %>
<div class="page-header">
  <h1>Nové letiště</h1>
</div>

<%= render 'form' %>

app/views/airports/show.html.erb
<% provide(:title, "- Letiště #{@airport.name}") %>
<div class="page-header">
  <h1>Letiště <%= @airport.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Země</dt>
  <dd><%= link_to @airport.state.name, @airport.state %></dd>
  <dt>Počet letů</dt>
  <dd><%= @airport.count_trips %></dd>
</dl>

<b>Tabulka Odletů</b>
<table class="table table-hover table-striped">
  <thead>
  <tr>
    <th>Odkud</th>
    <th>Kam</th>
    <th>Čas odletu</th>
    <th>Čas příletu</th>
    <th>Počet míst</th>
    <th>Počet volných míst</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @airport.departures.each do |trip| %>
      <tr>
        <td><%= link_to trip.from.name, trip.from %></td>
        <td><%= link_to trip.to.name, trip.to %></td>
        <td><%= trip.departure.strftime('%e.%m.%Y %H:%M') %></td>
        <td><%= trip.arrival.strftime('%e.%m.%Y %H:%M') %></td>
        <td><%= trip.airplane.count_seats %></td>
        <td><%= trip.free_tickets %></td>
        <td><%= link_to 'Smazat', trip_path(trip), :method => :delete,
                        :confirm => 'Opravdu chcete smazat tuto zemi?',
                        :class => 'btn btn-medium btn-danger' %>
          <%= link_to 'Editovat', edit_trip_path(trip), :class => 'btn btn-medium btn-info' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<b>Tabulka Příletů</b>
<table class="table table-hover table-striped">
  <thead>
  <tr>
    <th>Odkud</th>
    <th>Kam</th>
    <th>Čas odletu</th>
    <th>Čas příletu</th>
    <th>Počet míst</th>
    <th>Počet volných míst</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @airport.arrivals.each do |trip| %>
      <tr>
        <td><%= link_to trip.from.name, trip.from %></td>
        <td><%= link_to trip.to.name, trip.to %></td>
        <td><%= trip.departure.strftime('%e.%m.%Y %H:%M') %></td>
        <td><%= trip.arrival.strftime('%e.%m.%Y %H:%M') %></td>
        <td><%= trip.airplane.count_seats %></td>
        <td><%= trip.free_tickets %></td>
        <td><%= link_to 'Smazat', trip_path(trip), :method => :delete,
                        :confirm => 'Opravdu chcete smazat tuto zemi?',
                        :class => 'btn btn-medium btn-danger' %>
          <%= link_to 'Editovat', edit_trip_path(trip), :class => 'btn btn-medium btn-info' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>