config/routes.rb
Rails.application.routes.draw do

   root 'ticket_portal#portal'

   resources :airports, :states, :users, :user_sessions, :airplanes, :trips, :tickets

   get 'faq' => 'static_pages#faq', :as => :faq
   get 'contacts' => 'static_pages#contacts', :as => :contacts
   get 'terms' => 'static_pages#terms', :as => :terms

   get 'login' => 'user_sessions#new', :as => :login
   get 'logout' => 'user_sessions#destroy', :as => :logout

   get 'panel' => 'admin_pages#panel', :as => :panel

   get 'portal' => 'ticket_portal#portal', :as => :portal
   get 'search' => 'ticket_portal#search', :as => :search
   get 'my_tickets' => 'ticket_portal#my_tickets', :as => :my_tickets

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base

  has_many :trips
  has_many :airplane_classes, :inverse_of => :airplane

  def count_seats
    seats = 0
    self.airplane_classes.each do |c|
      seats += c.seats
    end
    seats
  end

  validates_presence_of :name
  validates_uniqueness_of :name
  accepts_nested_attributes_for :airplane_classes, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/models/airplane_class.rb
class AirplaneClass < ActiveRecord::Base

  belongs_to :airplane
  has_many :tickets

  def get_title
    "#{self.name} / +#{self.plus_price} Kč"
  end

  validates_presence_of :name, :plus_price, :seats
end

app/models/airport.rb
class Airport < ActiveRecord::Base

  belongs_to :state

  has_many :departures, :class_name => 'Trip', :foreign_key => :from_airport_id
  has_many :arrivals, :class_name => 'Trip', :foreign_key => :to_airport_id

  def count_trips
     departures.count + arrivals.count
  end

  validates_presence_of :name, :state_id
end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :airports

  validates_presence_of :name
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  belongs_to :user
  belongs_to :airplane_class, :class_name => 'AirplaneClass', :foreign_key => :class_id
  belongs_to :trip

  def count_price
    self.trip.base_price + self.airplane_class.plus_price
  end

  validates_presence_of :trip_id, :class_id, :user_id
end

app/models/trip.rb
class Trip < ActiveRecord::Base

  belongs_to :from, :class_name => 'Airport', :foreign_key => :from_airport_id
  belongs_to :to, :class_name => 'Airport', :foreign_key => :to_airport_id
  belongs_to :user
  has_many :tickets

  belongs_to :airplane

  def free_tickets?
    if self.tickets.count < self.airplane.count_seats
      true
    else
      false
    end
  end

  def free_tickets
    self.airplane.count_seats - self.tickets.count
  end

  def duration
    Time.diff(Time.parse(self.arrival.to_s), Time.parse(self.departure.to_s), '%h:%m')[:diff]
  end


  validates_presence_of :from_airport_id, :to_airport_id, :base_price, :airplane_id, :departure, :arrival, :base_price
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |auth|
  end

  has_many :trips
  has_many :tickets


  def is_admin?
    if self.level == 'admin'
      true
    else
      false
    end
  end

  def is_online?
    if self.last_request_at.nil?
      return false
    else
      if self.last_request_at > 15.minutes.ago
        return true
      else
        return false
      end
    end
  end

  validates_presence_of :email, :on => :create
  validates_presence_of :password_confirmation, :on => :create
  validates_presence_of :email_confirmation, :on => :create
  validates :email, :confirmation => true, :on => :create
  validates :password, :confirmation => true, :on => :create

  validates :email, :uniqueness => true
  validates :login, :uniqueness => true
  validates :login, :length => {:minimum => 4, :maximum => 16}
  validates :password, :length => {:minimum => 6}, :on => :create
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end
end

app/controllers/trips_controller.rb
# encoding: utf-8

class TripsController < ApplicationController

  before_filter :request_admin
  layout 'admin'

  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trips_path, notice: 'Let vytvořen.' }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_path, notice: 'Let smazán.' }
      format.json { head :no_content }
    end

  rescue ActiveRecord::RecordNotFound
    return redirect_to trips_path, alert: 'Let nenalezen.'
  end

  def new
    @trip = Trip.new

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def edit
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to trips_path, alert: 'Let nenalezen.'
  end

  def index
    @trips = Trip.all

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  rescue ActiveRecord::RecordNotFound
    return redirect_to root_path, alert: 'Let nenalezen.'
  end

  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(trip_params)
        format.html { redirect_to trips_path, notice: 'Let byl upraven.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  protected
  def trip_params
    params.require(:trip).permit(:from_airport_id, :to_airport_id, :base_price, :airplane_id, :departure, :arrival)
  end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<noscript>
  <div class="alert alert-block alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Javascript je vypnutý!</h4>
    Bez Javascriptu L-ternative nebude fungovat správně, prosím povolte ho ve svém prohlížeči.
  </div>
</noscript>

<% if notice %>
    <div class="alert alert-block alert-info">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <h4 class="alert-heading">Upozornění</h4>
      <%= notice %>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-block alert-error">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <h4 class="alert-heading">Chyba</h4>
      <%= alert %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid" style="margin-top: 4em;">
  <div class="col-md-12">
    <p>@2014 Super Letenky inc.</p>
    <%= link_to 'FAQ', faq_path %> | <%= link_to 'Kontakty', contacts_path %>
  </div>
</div>

app/views/layouts/_navbar_admin.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-bar"></span>
      </button>
      <%= link_to 'Letenky', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to('Administrační panel', panel_path) %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to(current_user.login, user_path(current_user))%></li>
            <li><%= link_to('Odhlášení', logout_path) %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_normal.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-bar"></span>
        <span class="glyphicon glyphicon-bar"></span>
      </button>
      <%= link_to 'Letenky', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to('FAQ', faq_path) %></li>
        <li ><%= link_to('Kontaky', contacts_path) %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <% if current_user.is_admin? %>
                <li><%= link_to('Administrace', panel_path) %></li>
            <% end %>
            <li><%= link_to(current_user.login, user_path(current_user))%></li>
            <li><%= link_to('Odhlášení', logout_path) %></li>
        <% else %>
            <li><%= link_to('Registrace', new_user_path) %></li>
            <li><%= link_to('Přihlášení', login_path) %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letenky administrace <%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'layouts/navbar_admin' %>

<div class="container-fluid" style="margin-top: 6em;">
  <%= render :partial => 'layouts/flash' %>
  <div class="col-md-2 well">
    <ul class="nav nav-list">
      <li class="nav-header">
        <b>Letiště</b>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-home') + ' Seznam', airports_path %>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-plus') + ' Nové letiště', new_airport_path%>
      </li>
      <li class="nav-header">
        <b>Země</b>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-globe') + ' Seznam', states_path %>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-plus') + ' Nová země', new_state_path %>
      </li>
      <li class="nav-header">
        <b>Letadla</b>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-plane') + ' Seznam', airplanes_path %>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-plus') + ' Nové letadlo', new_airplane_path%>
      </li>
      <li class="nav-header">
        <b>Lety</b>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-share-alt') + ' Seznam', trips_path %>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-plus') + ' Nový let', new_trip_path%>
      </li>
      <li class="nav-header">
        <b>Uživatelé</b>
      </li>
      <li>
        <%= link_to content_tag(:i, ' ', :class => 'glyphicon glyphicon-user') + ' Seznam', users_path %>
      </li>
    </ul>
  </div>
  <div class="col-md-10">
    <%= yield %>
  </div>
</div>

<%= render :partial => 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letenky! <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'layouts/navbar_normal' %>

<div class="container-fluid" style="margin-top: 6em;">
  <%= render :partial => 'layouts/flash' %>
  <div class="col-md-12">
    <%= yield %>
  </div>
</div>

<%= render :partial => 'layouts/footer' %>

</body>
</html>